name: tasklist_recipes_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  dartz: ^0.10.1
  dio: ^5.5.0+1
  fancy_password_field: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_onboarding_slider: ^1.0.11
  get_it: ^7.7.0
  logger: ^2.3.0
  pinput: ^5.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
