name: tasklist_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.14.0
  dio: ^5.5.0+1
  get_it: ^7.7.0
  logger: ^2.3.0
  mongo_dart: ^0.10.3
  

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
